### PR TITLE
Remove quotes from table_name.

### PR DESCRIPTION
**Pull request by erictheise**
@benfry, I initially [submitted this pr to fjenett/sql-library-processing](https://github.com/fjenett/sql-library-processing/pull/17) but yours seems to be the most up to date branch. Bit confusing. Anyway.

I'm seeing this error when trying to connect a Processing 3.3.7 sketch to my local PostgreSQL database
```
postgres=# ERROR:  syntax error at or near "'table_name'" at character 19
STATEMENT:  SELECT relname AS 'table_name' FROM pg_stat_user_tables WHERE schemaname='public'
```
and it's the same one discussed in this [forum thread from 2015](https://forum.processing.org/two/discussion/11259/about-beziersqlib-with-postgresql).

Would really rather not resort to something other than PostgreSQL. Happy to get any guidance or feedback on how to address this, thanks.

### CODE REVIEW

**Comment by benfry** [comment]
Huh, thanks. Yeah, I wound up doing this because a lot of people were using the library and it needed a fix that was just a line or two. But uh, not looking to be the maintainer… :)

**Comment by ghost** [comment]
PLEASSEEE, build a jar file without quotes in table_name inside PostgreSQL.java =(

**Comment by benfry** [comment]
Hi @wellton. Again, this isn't my project, but I've just posted an update with the fix. 

It may take a little while to show the new version inside the Library Manager, though you could try setting aside the old version, and then re-installing, or download from [here](https://github.com/benfry/sql-library-processing/blob/master/release/BezierSQLib.zip). 

I've not tested this release, so keep around the old one just in case.

**Comment by ghost** [comment]
SHOWWW... its Works. Thanks @benfry  =)

captura de tela de 2019-02-10 15-33-47

**Pull request merged**
